name: cyborg
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4  
  firebase_auth: ^5.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Correctly placed inside dev_dependencies
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/monogram2-01.png" 
  adaptive_icon_foreground: "lib/assets/monogram2-01.png"  
  adaptive_icon_background: "#ffffff" 

flutter_native_splash:
  color: "#000000"  
  image: "lib/assets/monogram2-01.png" 
  android: true
  ios: true
  fullscreen: true


flutter:
  uses-material-design: true

  # Ensure assets directory is recognized
  assets:
    - lib/assets/monogram2-01.png

