// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkpR_J2oVXIIv8WYkEoMhxCklIQkcUMI',
    appId: '1:984915505078:web:c92ee4e8cd090f3e775b17',
    messagingSenderId: '984915505078',
    projectId: 'cyborg-app-flutter',
    authDomain: 'cyborg-app-flutter.firebaseapp.com',
    storageBucket: 'cyborg-app-flutter.firebasestorage.app',
    measurementId: 'G-Q26CSM58YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4lP26tbiyqqLx8uPtu6_qCXEUsazUrY',
    appId: '1:984915505078:android:fb2cdd93a361a5b0775b17',
    messagingSenderId: '984915505078',
    projectId: 'cyborg-app-flutter',
    storageBucket: 'cyborg-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQWReYdPXrTr2iR0FQ1TyTmcdIKsiNiE',
    appId: '1:984915505078:ios:24b03de443756f4b775b17',
    messagingSenderId: '984915505078',
    projectId: 'cyborg-app-flutter',
    storageBucket: 'cyborg-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.cyborg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdQWReYdPXrTr2iR0FQ1TyTmcdIKsiNiE',
    appId: '1:984915505078:ios:24b03de443756f4b775b17',
    messagingSenderId: '984915505078',
    projectId: 'cyborg-app-flutter',
    storageBucket: 'cyborg-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.cyborg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkkpR_J2oVXIIv8WYkEoMhxCklIQkcUMI',
    appId: '1:984915505078:web:6d56d2e2cae48ac3775b17',
    messagingSenderId: '984915505078',
    projectId: 'cyborg-app-flutter',
    authDomain: 'cyborg-app-flutter.firebaseapp.com',
    storageBucket: 'cyborg-app-flutter.firebasestorage.app',
    measurementId: 'G-KXW4ZHMWSE',
  );
}
